project:
  type: website
  output-dir: docs

website:
  title: "Natalie Wiley"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "GHG Inventory Projects"
        menu:
          - Risk_Assessment.qmd
          - Electricity_emissions.qmd
          - Transportation_Emissions.qmd
          - Emission_Factors.qmd
          - Datagaps.qmd
          - Urea_Emissions.qmd
          - SOC_change_montecarlo.qmd
          - N2O_SoilEmissions.qmd
      - href: Geospatial.qmd
        text: "Geospatial Analysis"
      - href: COB_report.qmd
        text: "Sustainability Assessments"
      - href: Bison_storymap.qmd
        text: "COP27 Presentation"
         

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    

editor: visual

